# Order Service - Production

AllowedHosts: "*"

Logging:
  LogLevel:
    Default: "Warning"
    Microsoft.AspNetCore: "Warning"

Order:
  Database:
    CommandTimeoutSec: 30
    EnableRetry: true
    MaxRetryCount: 5
