# Gateway - Production

AllowedHosts: "*.azurecontainerapps.io"

Logging:
  LogLevel:
    Default: "Warning"
    Microsoft.AspNetCore: "Warning"
    Yarp: "Warning"

Gateway:
  Authentication:
    Enabled: true

  RateLimiting:
    PermitLimit: 1000
    WindowSeconds: 60
