# Product Service - Production

AllowedHosts: "product-service.internal.*.azurecontainerapps.io,localhost"

Logging:
  LogLevel:
    Default: "Warning"
    Microsoft.AspNetCore: "Warning"

Product:
  Database:
    CommandTimeoutSec: 30
    EnableRetry: true
    MaxRetryCount: 5

  Cache:
    Enabled: true
    ExpirationMin: 120
